### ISSUE TITLE
Not working in Cygwin/Mintty

### ISSUE THREAD

**Issue by raoulh** [howeyc/gopass#34]
The password is still echoed when running the binary in cygwin/mintty

**Comment by havoc-io** [comment]
I created a [fork](https://github.com/havoc-io/gopass/tree/winposix) that supports mintty-based consoles, but it's *very* hackish and probably not the most robust option. Unfortunately there'll never really be a more elegant way to do this in Go (AFAIK) because it would require using CGO to link with mintty libraries that wouldn't exist in the general case (your binary would only run in Cygwin/MinGW environments and might have version issues), and it would still probably require a fork to manage the build constraints.

The best option is really just to use the `winpty` wrapper that almost all Cygwin and MinGW distributions ship with (just prefix any command using this library with `winpty`).  This does use the C libraries that are shipped with the corresponding mintty distribution and is far more elegant.  This also fixes a lot of problems not related to echoing, e.g. background processes hanging a mintty shell.

**Comment by howeyc** [comment]
This looks interesting. If there's a way to have the library continue to behave as expected on machines without Cygwin/MinGW and also support mintty-based consoles I'm all for it.

Upon cursory look at your fork I'm not sure it will work without Cygwin/MinGW installed.

**Comment by havoc-io** [comment]
This fork should work in cmd.exe environments, even without a Cygwin/MinGW
environment installed. It relies on checking whether or not the stty
command exists (if it doesn't, a cmd.exe environment is assumed). This is
why it's a bit hackish in my opinion. Also a potentially a bit slow, but in
practice the overhead is imperceptible.

**Comment by howeyc** [comment]
What if I'm using cmd.exe and have stty installed? Does it do something weird?

**Comment by havoc-io** [comment]
Well, it's a heuristic, to be sure.  This is why I never opened a PR for
this fork - it seemed too hacky (though you're of course welcome to use
it).  winpty is really the canonical way to do this.  Fortunately stty
shouldn't appear in your cmd.exe PATH, even if installed somewhere for
Cygwin or MinGW.

In the case you describe, it would depend on how the stty command behaves
in the context of your cmd.exe environment.  Some stty commands might be
translated down correctly, but I wouldn't count on it.

**Comment by howeyc** [comment]
Oh, okay.

**Comment by havoc-io** [comment]
Actually, it's also possible that stty would just fail in a cmd.exe
environment, which would cause the code in the fork to just fall back to
the standard cmd.exe methods.  mintty environments use a complicated setup
of named pipes to do their work, and I think if stty can't detect these, it
would just bail, which the fork would interpret as not being a POSIX
environment. So it could just work. The danger would be an stty command
that made some changes but not all. The assumption right now is that stty
is just pass/fail, which should be a pretty decent assumption since the
stty commands being used are very standard.  It might be worth testing what
happens if one manually adds a mintty stty executable to a cmd.exe path. I
suspect the current fork code would just work as long as stty gives up
immediately.

**Comment by howeyc** [comment]
No longer maintained.
