### ISSUE TITLE
getPassMasked fails on windows in git bash

### ISSUE THREAD

**Issue by groenborg** [howeyc/gopass#39]
when using running getPassMasked on windows terminal emulators like git bash and Cmder, the password it not masked and is printed after it is submitted. 

I am running on golang version 1.9

**Comment by johnSchnake** [comment]
I haven't taken a look at this in a while but based on my memory I don't think there is a very feasible way to get this to work.

The masking happens by making syscalls to change the cmdline behavior and if you are using a program that ignores syscalls there isnt a standard way to know what to do.

Effectively each terminal emulator would need to have a hook to specify how to modify its own behavior and gopass would have to know which to call or just call them all.

I ran into issues with the same root cause when trying to do stdlib go stuff + cygwin terminal.

**Comment by johnSchnake** [comment]
Same as #34 effectively.

**Comment by CamilleZxt** [comment]
Is there a solution now

**Comment by johnSchnake** [comment]
I think the readme says it best at this point:

> You should probably just use terminal.

A lot has been developed for the go stdlib terminal package since this was originally developed and I dont know if it has much to offer at this point. Lots of examples to find in other repos of its use too.

Good luck

**Comment by howeyc** [comment]
No longer maintained.
